### ISSUE TITLE
Increased configuration items

### ISSUE THREAD

**Issue by dc932dc** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#106]
![图片](https://user-images.githubusercontent.com/46415893/230179324-654fbbba-8dc3-45df-81fa-6ef248f50bda.png)
希望能关闭这卡片 尝试过注释法无效果
![图片](https://user-images.githubusercontent.com/46415893/230179404-ef51cea0-13c1-4e06-8051-19f290ecda41.png)

**Comment by rootlexme** [comment]
已在dev分支修复
