### ISSUE TITLE
外挂标签

### ISSUE THREAD

**Issue by Ezgx** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#109]
要不要考虑集成一下butterfly传统

**Comment by adil-zhang** [comment]
暂时不考虑在主题中内置过多的外挂标签，仅保留部分基础的。
看到您这边已经提交了PR，非常感谢您的贡献，建议您写上教程，后续我们会将您的教程在合适的地方引入让更多主题用户看到。
再次感谢您的贡献。

**Comment by Ezgx** [comment]
> 暂时不考虑在主题中内置过多的外挂标签，仅保留部分基础的。 看到您这边已经提交了PR，非常感谢您的贡献，建议您写上教程，后续我们会将您的教程在合适的地方引入让更多主题用户看到。 再次感谢您的贡献。

教程https://ezgx.site/2023/tagplugins/

如果要添加外挂标签的教程，我会再写一篇。
