### ISSUE TITLE
还没发啊（）

### ISSUE THREAD

**Issue by Ezgx** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#110]
![image](https://user-images.githubusercontent.com/110729988/230772107-f3d8eb69-ea53-4a76-a60b-4ec92a761a48.png)

**Comment by adil-zhang** [comment]
目前主题还处于内测阶段，仅小范围用户在使用，后续主题整体健壮之后，会在官网中将主题发布。
感谢您的持续支持
