### ISSUE TITLE
文章头图部分

### ISSUE THREAD

**Issue by Ethereal-sakura** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#116]
![image](https://user-images.githubusercontent.com/110333012/232179298-60c5d61d-ddcc-4c5c-bf6a-67d1769bdfca.png)
在没有设置 分类的情况下，能否把原创右端的透明框给去掉呀？

**Comment by adil-zhang** [comment]
感谢您的反馈，已在DEV中修复
