### ISSUE TITLE
友链朋友圈往下滑动，顶部没有底图固定区域。当前页面刷新可以

### ISSUE THREAD

**Issue by wygwyggit** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#120]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/52059667/232479193-a74fdfe9-0baa-4d71-b8f5-3addb9faebd1.png">

**Comment by adil-zhang** [comment]
非主题内置内容，请仔细阅读鱼塘相关魔改信息。或提供在线地址查看详细问题。

**Comment by adil-zhang** [comment]
已实测部署鱼塘，并未发现此问题。
