### ISSUE TITLE
标签彩色

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#121]
是否考虑实现以下效果
<img width="481" alt="image" src="https://user-images.githubusercontent.com/22308895/232522306-58418049-48c0-47e6-8073-965a1becb48e.png">

**Comment by adil-zhang** [comment]
调整CSS 中`#post .tag_share .post-meta__tags`的`background`为自己喜欢的颜色即可。

**Comment by cunyu1943** [comment]
ok
