### ISSUE TITLE
页面如何隐藏评论

### ISSUE THREAD

**Issue by jkjoy** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#127]
![image](https://user-images.githubusercontent.com/23159890/234746378-f5b8bfbb-ade7-4a5d-878f-ea72cad68f0b.png)

**Comment by jkjoy** [comment]
用butterfly是可以的,用了这个主题就失效了

**Comment by rootlexme** [comment]
您可以使用comment: false隐藏

**Comment by jkjoy** [comment]
> 您可以使用comment: false隐藏

好的谢谢~
