### ISSUE TITLE
宝藏博主，随机友链跳转

### ISSUE THREAD

**Issue by IonRh** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#132]
宝藏博主随机友链跳转必须开启配置中的下图所示
![Y0V5K6}X)T4CEQM2KF(K4UF](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/102129419/f75588ba-ebd6-4231-bef0-744daf567a49)
不然会报错：
![ELG5_7L F L` P}IO5`065O](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/102129419/2799b587-c5f1-42b6-9b7e-8fd29f278933)
但是开启之后在页脚底部会出现如下图所示：
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/102129419/c2032eda-15b0-467f-9e0e-6188574fa172)
建议，默认开启随机跳转，且上面的配置项调整为关于页脚友链的显示与不显示

**Comment by adil-zhang** [comment]
此问题在 #89 反馈，待修复。
另外如果您仔细阅读文档之后，您一定会在[主题文档这里](https://next-docs.acrylic.org.cn/configuration/footer)看到`ramdonlink: false`为**开启页脚随机友链**的配置项。
感谢您的反馈。
