### ISSUE TITLE
github仓库建议开一个讨论

### ISSUE THREAD

**Issue by Mitpoppy** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#142]
会更有利于用户交流

**Comment by adil-zhang** [comment]
我们有用户交流群QQ：649565726

**Comment by rootlexme** [comment]
@adil-zhang 你觉得有必要吗

**Comment by adil-zhang** [comment]
> @adil-zhang 你觉得有必要吗

可以先开看看效果，我看pro开了之后似乎也没人多去关注，用discussions的人还是少……
顺带说一下，主题start 破百了 😍

**Comment by rootlexme** [comment]
> > @adil-zhang 你觉得有必要吗
> 
> 可以先开看看效果，我看pro开了之后似乎也没人多去关注，用discussions的人还是少……
> 顺带说一下，主题start 破百了 😍

我也觉得暂时没什么必要
