### ISSUE TITLE
内容过长时，目录不匹配

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#146]
内容已经到了 50，但目录最长只能拉倒 35
<img width="1551" alt="image" src="https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/22308895/90a15957-35e7-4e48-bccd-1b10c908cf2d">

**Comment by adil-zhang** [comment]
我查看了你的地址，似乎是因为你的插件的问题，此问题在我本地并未复线，请查看：https://blog.adil.com.cn/posts/79a7aba4.html
