### ISSUE TITLE
代码块显示异常，白色背景下代码看不见，代码块位置异常

### ISSUE THREAD

**Issue by unfalltable** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#151]
![3ff9f30f46ac64436b48d993303f996](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/91110716/ca68e62b-e256-4c81-9b5d-504660ff8879)

**Comment by adil-zhang** [comment]
您好，什么都没有，我们无法为您排错

**Comment by adil-zhang** [comment]
请提供线上地址。

**Comment by rootlexme** [comment]
@adil-zhang 这似乎是一个bug

**Comment by unfalltable** [comment]
> 您好，什么都没有，我们无法为您排错

https://unfalltable.github.io/

**Comment by adil-zhang** [comment]
> @adil-zhang 这似乎是一个bug

他提供地址了，回头我看看怎么回事

**Comment by freelancelwj7** [comment]
请问，怎么添加代码块的复制功能？看了一遍文档，没找到

**Comment by adil-zhang** [comment]
> 请问，怎么添加代码块的复制功能？看了一遍文档，没找到

hightlight: true

**Comment by unfalltable** [comment]
代码块是md的语法，格式为：```java

**Comment by unfalltable** [comment]
我怀疑是无序列表和代码块一起使用的导致的

**Comment by rootlexme** [comment]
> 我怀疑是无序列表和代码块一起使用的导致的

大概是css样式的问题

**Comment by adil-zhang** [comment]
@unfalltable  可以把你的这篇文章的MD发我吗，我在本地复线一下，然后排查下问题。https://unfalltable.github.io/2023/06/08/面试/八股文/Questions/

**Comment by unfalltable** [comment]
> @unfalltable 可以把你的这篇文章的MD发我吗，我在本地复线一下，然后排查下问题。[https://unfalltable.github.io/2023/06/08/面试/八股文/Questions/](https://unfalltable.github.io/2023/06/08/%E9%9D%A2%E8%AF%95/%E5%85%AB%E8%82%A1%E6%96%87/Questions/)

https://github.com/unfalltable 这里拿吧

**Comment by adil-zhang** [comment]
> > 我怀疑是无序列表和代码块一起使用的导致的
> 
> 大概是css样式的问题

@rootlexblog  我仔细看了下，这并不是CSS的问题，在无序列表与代码块同时存在时，会发生一些异常。渲染出来的文章整体结构都发生了变化。

**Comment by adil-zhang** [comment]
@unfalltable  我查看了你的代码与相关问题，这是hexo渲染器的问题，现在有两种解决方案：
1.你需要调整你所有代码相关内容，取消 列表与代码块同时使用的情况。
 ```
-  ```xml
        <settings> <setting name="mapUnderscoreToCamelCase" 
                value="true"/>    </settings>
        ```

```
调整为 
```
   ```xml
        <settings> <setting name="mapUnderscoreToCamelCase" 
                value="true"/>    </settings>
        ```

```
2. 调整语法，还是上述的例子，将内容调整为：

```
  - {% codeblock lang:html %}
     <settings>
    	<setting 
            name="mapUnderscoreToCamelCase" 
            value="true"/>   
    </settings>
   {% endcodeblock %}
```

希望对你有所帮助。
