### ISSUE TITLE
meta疑问及front-matter参数疑问

### ISSUE THREAD

**Issue by yamonc** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#153]
您好，感谢您的项目开源，在项目的使用中，有诸多疑问想问下您
1. 在conf_acrylic文件中已经配置meta的属性值，但是页面上没有体现，麻烦您看下，这块是有什么问题吗？
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/52881289/b95e23d0-ebe0-42aa-928c-bf2828f17672)
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/52881289/6d127320-2f82-4756-a60a-a20abcf0f823)
2. 发布博客的封面是有自己专门的图库服务器吗？或者说，在发布博客的时候对cover参数怎么写值？
3. 可不可以给出一个关于[Front-matter](https://next-docs.acrylic.org.cn/configuration/page#front-matter)的示例：
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/52881289/42a3031d-e82f-4b84-834a-a1d548fb8fea)
多谢多谢。

**Comment by adil-zhang** [comment]
- 字数统计，阅读时长依赖插件 `hexo-wordcount`，PV，热度依赖 twikoo，需要自己百度部署twikoo，然后在主题配置文档中添加地址即可。
- 自己博客图片需要放在自己图床中，或使用公共图床。 给你个我自己的例子：`cover: 'https://p.adil.com.cn/2021-04-12-SAP.png'`
- Front-matter 在主题文档中已经有很详细的解释了，按需配置即可。

欢迎加入我们的QQ交流群：853154994

**Comment by yamonc** [comment]
> * 字数统计，阅读时长依赖插件 `hexo-wordcount`，PV，热度依赖 twikoo，需要自己百度部署twikoo，然后在主题配置文档中添加地址即可。
> * 自己博客图片需要放在自己图床中，或使用公共图床。 给你个我自己的例子：`cover: 'https://p.adil.com.cn/2021-04-12-SAP.png'`
> * Front-matter 在主题文档中已经有很详细的解释了，按需配置即可。
> 
> 欢迎加入我们的QQ交流群：853154994

好的，多谢您的回复。
