### ISSUE TITLE
文档写的内容太少了

### ISSUE THREAD

**Issue by everfu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#159]
请问如何配置友链界面，还有一些页面中的细节，文档写的太少了，谢谢，劳烦告知

**Comment by adil-zhang** [comment]
请您仔细阅读文档，您的友链配置界面见 [这里](https://next-docs.acrylic.org.cn/configuration/page#友情链接)

**Comment by everfu** [comment]
看到了，谢谢

**Comment by everfu** [comment]
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/04633ba9-4c24-47cb-ada3-59ce29a605b3)

我遇到一个问题
