### ISSUE TITLE
我收集的一些使用上仍然存在的Bug

### ISSUE THREAD

**Issue by everfu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#161]
- 分类中含有子分类显示出错（在下方仍然显示）
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/3fd03047-01a0-476f-b4ec-1195c774ad16)
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/e69ef911-f13b-468a-a3d0-110e3abe230b)

- 友链数量过少，随机显示出现重复
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/b805d3a4-7a61-4f73-94ca-6b7c78833fae)
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/873bf9bf-ed3d-4846-8334-4b1b94a3addd)

**Comment by everfu** [comment]
- 瞬间顶部banner图左上角文字过小
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/c4ede3d2-de21-40f4-88eb-c29c4b5b5501)

**Comment by everfu** [comment]
> 

我错了，这个友链应该没问题，我重复添加了
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/1d3c2c61-38c2-4fac-9667-c1fa32c71118)

**Comment by adil-zhang** [comment]
> * 瞬间顶部banner图左上角文字过小
>   ![image](https://user-images.githubusercontent.com/74389842/246815870-c4ede3d2-de21-40f4-88eb-c29c4b5b5501.png)

可自行调整CSS至你喜欢的样子

**Comment by adil-zhang** [comment]
一个文章三个分类，请自行调整文章内容。
多个问题请分不同issues，感谢配合。

感谢您的使用与认可。
