### ISSUE TITLE
增加日夜切换功能

### ISSUE THREAD

**Issue by everfu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#162]
希望能添加一个根据博客所在时区或者自定义时间段切换为夜间或者白天模式。

**Comment by adil-zhang** [comment]
为了更人性化，主题默认根据浏览器模式来统一调整。
如果设定时间到了，但是你的浏览器没变黑，而博客变黑了，给人的体验很差，不是吗？
