### ISSUE TITLE
请求加入 标签外挂

### ISSUE THREAD

**Issue by everfu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#166]
请求添加 note 主题中的标签外挂功能：
如下语法：
- ~~tabs~~ (主题已添加)
- timeline 时间线
- galleryGroup 相册图库
- gallery 相册
- tag-hide 隐藏按钮
- mermaid 图表

非常需要这样的功能，很方便

https://www.cnblogs.com/niaobulashi/p/16085666.html

**Comment by adil-zhang** [comment]
根据教程自行引入。
