### ISSUE TITLE
建议接入 giscus 评论

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#17]
- https://giscus.app/zh-CN

等一波完善的文档和功能后体验，会一直关注的 😄

**Comment by rootlexme** [comment]
您好，感谢您对本项目的支持，giscus 评论系统可以考虑添加，不过用的人好像不是很多，而且魔改样式比较麻烦，所以短期内不会去适配。
