### ISSUE TITLE
发现一个即刻短文中的bug

### ISSUE THREAD

**Issue by everfu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#171]
当我添加的内容中出现html代码时，当前短文的回复按钮会出现如下情况：
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/cc61e4c0-835a-4603-93b0-6b26050cc361)
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/3928ad58-a44d-4877-8159-4283a561102a)
多出 `')" >`这样一串
修改`saysBottom.ejs`中如下位置（13 - 17行）：
```html
# 原代码
<a class="bber-reply" onclick="acrylic.toTalk('<%- item.content %>')" >
        <i class="fa-solid fa-comment" style="font-size: 1rem;">
        </i>
</a>
# 修改后
<a class="bber-reply" onclick='acrylic.toTalk("<%- item.content %>")' >
        <i class="fa-solid fa-comment" style="font-size: 1rem;">
        </i>
</a>

# 修改位置 
原："acrylic.toTalk('<%- item.content %>')"
改：'acrylic.toTalk("<%- item.content %>")'
```
得到解决

**Comment by everfu** [comment]
可有可无的bug，essay提供了一个image
```xml
   - content: [内容]
     image:
       - img1
       - img2
       - img3
       ...
     date: [日期]
```

**Comment by wleelw** [comment]
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/8a29aa77-19f7-4ddf-8f5d-88f4dc1f1bcf)
