### ISSUE TITLE
加入Butterly标签外挂

### ISSUE THREAD

**Issue by sysfox** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#178]
从Butterfly主题转到Acrylicy时遇到了很多问题，其中之一就是标签外挂，因为Acrylic似乎并不支持这一功能。
希望作者能在其中加入Butterfly的原生标签外挂，比较实用，同时也省去了主题转换、标签外挂自身设计的麻烦

**Comment by adil-zhang** [comment]
此主题与Acrylicy无关，由设计师heo设计，使用next.js开发。
