### ISSUE TITLE
发现一个控制台的bug

### ISSUE THREAD

**Issue by everfu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#179]
这里生成的路径是`/archives/2023-06/`
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/6ed0ee8d-5549-487d-9279-c8f45e9ce031)
而真实的路径是`/archives/2023/06/`
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/9a3bd015-eff4-4d31-a549-1d1fe049c435)

**Comment by everfu** [comment]
看来是主题的问题
Adil的也是如此
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/4345d03d-cd1e-40c0-9b04-54e1ba174d1c)

**Comment by everfu** [comment]
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/18a089a4-e4c9-46f3-82b1-53284d6e8d64)
暂时修改了一下，有其他更好的解决方案吗？

**Comment by adil-zhang** [comment]
[🐞 fix: 控制台归档路径异常](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/commit/e7cd5fa622b1db0a8a7b14d9448dcf87c0d57cab)

**Comment by everfu** [comment]
> 🐞 fix: 控制台归档路径异常

👌
