### ISSUE TITLE
主题配置文件不生效

### ISSUE THREAD

**Issue by khmoyu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#18]
本地预览_config.Acrylic.yml的配置是正常显示的，github action自动部署到仓库后_config.Acrylic.yml的配置没有生效，显示的的配置是主题文件夹中

**Comment by rootlexme** [comment]
看看是不是主题文件夹命名的问题

**Comment by khmoyu** [comment]
应该不是，我是按照主题文档弄的，并且本地预览是没有问题的，上传源码让其自动部署才出现了主题配置文件不生效的问题

**Comment by RainVice** [comment]
我使用的nodejs版本是18 ，在dev版本用Action自动部署能正常显示，stable版本显示一片空白
