### ISSUE TITLE
部署有问题

### ISSUE THREAD

**Issue by xiatianPE** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#180]
部署的时候出现了错误
Error: Process completed with exit code 255.

**Comment by xiatianPE** [comment]
问题解决了，但有新的问题
就是首页不显示显示空白
index.html 并没有写入代码

**Comment by adil-zhang** [comment]
请参照官方文档进行。
另：无报错误截图的情况下，没后任何人能帮你解决问题。

**Comment by xiatianPE** [comment]
> 请参照官方文档进行。
> 
> 另：无报错误截图的情况下，没后任何人能帮你解决问题。

已决解
