### ISSUE TITLE
说说页面音乐分享

### ISSUE THREAD

**Issue by pzjawa** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#181]
希望给说说页面添加音乐分享，支持音乐播放
https://blog.zhheo.com/essay/
![Snipaste_2023-07-12_16-51-48](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/113767212/f602762b-7329-4726-9e03-3b453e6bcdbd)
https://blog.anheyu.com/essay/
![Snipaste_2023-07-12_16-52-40](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/113767212/8cdf142c-1a12-4299-b1c3-d478dc4a95c0)

**Comment by adil-zhang** [comment]
[✨ feat: 即刻短文支持音乐播放](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/commit/f627bdc3b07ae1a2f9659b10b08beaf36e05b6a4)
说说新增配置项：
`music:
      id: 001lePVO36SNSo
      server: tencent`
完整配置项如下：
`  - content: 使用DEV最新版本，如有问题请提交issues反馈
    date: 2023-03-22 08:00:00
    link: https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/issues
    image:
      - https://p.adil.com.cn/uPic/n66Lr2.jpg.png
    music:
      id: 001lePVO36SNSo
      server: tencent`

**Comment by adil-zhang** [comment]
已在主题文档中更新配置
