### ISSUE TITLE
时间

### ISSUE THREAD

**Issue by xiatianPE** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#184]
![Screenshot_20230716_202320](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/121849812/c7b8f62a-6242-4550-b39d-b688d198e90c)
这时间怎么调整啊，看着好奇怪

**Comment by xiatianPE** [comment]
顺便帮我看这是什么问题
![Screenshot_20230716_204427](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/121849812/c1b859f5-a590-41a9-8f51-f7cd9e5e0da1)

**Comment by adil-zhang** [comment]
> ![Screenshot_20230716_202320](https://user-images.githubusercontent.com/121849812/253803697-c7b8f62a-6242-4550-b39d-b688d198e90c.jpg)
> 这时间怎么调整啊，看着好奇怪

时区问题，请调整hexo配置文档中的`timezone: Asia/Shanghai`

**Comment by adil-zhang** [comment]
> 顺便帮我看这是什么问题
> ![Screenshot_20230716_204427](https://user-images.githubusercontent.com/121849812/253804684-c1b859f5-a590-41a9-8f51-f7cd9e5e0da1.jpg)

缩进问题，请不要换行回车混用。

**Comment by xiatianPE** [comment]
![FE143BF7-96D7-4665-BD76-52B78ADB0C06](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/121849812/9ac780f3-aaaf-41c3-8f76-e65d5a689344)这又是什么问题？
