### ISSUE TITLE
又报错了

### ISSUE THREAD

**Issue by xiatianPE** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#185]
这个问题重复了好几遍了不知道是什么原因
![68BA77D8-6F7F-4036-BA11-F530FCD782F2](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/121849812/4192c2b0-6f40-4791-99dd-ac9e24e229b0)
![BB40D4DD-4267-43EE-8183-D04692248FCC](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/121849812/22dcb154-f976-4fc7-8c87-ae2cc9d53c43)

**Comment by adil-zhang** [comment]
请严格按照主题官方文档进行操作。
另，在您提出issues前，请确保您已经仔细阅读过文档、尝试过自己百度/谷歌或其他途径获取过报错原因。
