### ISSUE TITLE
侧边栏的问题

### ISSUE THREAD

**Issue by everfu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#186]
我自己抄了一个侧边栏组件，怎样把他移动到文章目录的下面，现在在最底下
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/673c3a77-5f50-4a0d-aea8-1e36b95069d0)

**Comment by adil-zhang** [comment]
侧边栏根据主题配置文档中的配置项`aside` ，在`layout/partial/compoment/aside/aside.ejs` 中循环调用`partial/compoment/aside/asideSwitch.ejs`生成。

**Comment by everfu** [comment]
这样么？没有效果哎，依然在最底部
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/0e6c71e7-043f-45d3-b94d-5fa5508ba439)
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/e468c8dd-4731-473b-a2e8-7f27cad953f8)

**Comment by adil-zhang** [comment]
看看你配置文件中的配置项`aside `

**Comment by wleelw** [comment]
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/e63c5217-59d1-4a7a-8b8a-5b960f6997bc)


> 看看你配置文件中的配置项`aside `

![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/444ed361-dae6-4417-9a9c-34dffad4ee0a)

**Comment by everfu** [comment]
> 看看你配置文件中的配置项`aside `

我知道了，谢谢，我知道哪里错了
