### ISSUE TITLE
about页面问题

### ISSUE THREAD

**Issue by Glannons** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#19]
全部拉去 https://blog.zhheo.com/about/ 页面，内容未做更改以及适配
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/49674345/223894706-b58e0f25-6d28-4c59-8332-782ccf2dce44.png">

**Comment by rootlexme** [comment]
已经在进行中。详见 #6
