### ISSUE TITLE
正在写朋友圈页面

### ISSUE THREAD

**Issue by everfu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#191]
抽空做了一个朋友圈页面，感觉代码过于简单了哈🤣，给你们看看

`circle.ejs`
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/5a137f46-636c-40b7-b6dc-25418b3da809)

`angle.ejs`
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/85ae018b-752f-487f-a675-32e223c2fc2e)

`heo.ejs`
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/08da80da-ce2d-4c17-96e8-fb23d065d1c2)

配置文件
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/70b11915-4964-4176-a93f-286c2f0eae97)

展示效果
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/1bd00a2e-84f5-472e-ba75-2c4146441f1b)

**Comment by wleelw** [comment]
root路径下 page.ejs 添加 case circle ，在circle.md中配置type属性为 `circle`

**Comment by everfu** [comment]
🤣感觉我写的代码有点多

**Comment by everfu** [comment]
教程链接：[为 Acrylic 添加朋友圈页](https://blog.sondy.top/posts/7f485ebb/)

**Comment by rootlexme** [comment]
如果您想要撰写教程并分享，请在discussion中发起，感谢您的配合

**Comment by wleelw** [comment]
> 如果您想要撰写教程并分享，请在discussion中发起，感谢您的配合

项目没打开 `discussion `
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/f13551e3-56e8-4efe-ba08-664342ece6d2)

**Comment by everfu** [comment]
> 如果您想要撰写教程并分享，请在discussion中发起，感谢您的配合

好的
