### ISSUE TITLE
页面跳转优化

### ISSUE THREAD

**Issue by everfu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#195]
我讲讲我怎么发现的，
进入首页，点击任意文章，点击左上角logo返回主页，页面会刷新。
进入首页，点击任意页面（非文章页面），点击左上角logo返回主页，页面保存状态，不会刷新。

我忘记怎么弄了，求助！

**Comment by everfu** [comment]
实现保存状态跳转效果

**Comment by rootlexme** [comment]
dom结构更新了

**Comment by everfu** [comment]
![image](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/74389842/bd81b9f5-6bdb-4263-907b-7dfc0c6379a0)
从文章页切换到普通页，pjax不一致报错，然后dom就刷新了
“DOM doesn’t look the same on new loaded page: ’title’ - new 1, old 2”

我不会pjax～，求助

**Comment by rootlexme** [comment]
> ![image](https://user-images.githubusercontent.com/74389842/255815133-bd81b9f5-6bdb-4263-907b-7dfc0c6379a0.png) 从文章页切换到普通页，pjax不一致报错，然后dom就刷新了 “DOM doesn’t look the same on new loaded page: ’title’ - new 1, old 2”
> 
> 我不会pjax～，求助

标题发生了变更，但pjax没有刷新
