### ISSUE TITLE
文章目录过多后，往下翻右侧目录列表不能正常跟随页面进度

### ISSUE THREAD

**Issue by adil-zhang** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#23]
[](https://test.adil.com.cn/posts/8b7a779f.html)
![VYG%42`IO(8$HUPDANCWCIF](https://user-images.githubusercontent.com/55967755/224068060-1a489d68-2241-4c04-b6d7-74c949c8007a.png)

**Comment by adil-zhang** [comment]
https://test.adil.com.cn/posts/8b7a779f.html

**Comment by rootlexme** [comment]
感谢您的反馈，已在dev分支实现
