### ISSUE TITLE
副标题未正常显示

### ISSUE THREAD

**Issue by adil-zhang** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#24]
[https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/blob/c54bc982e4201334ae5b9b36f3738d51142cbc5f/layout/partial/head.ejs#L7](url)

这行需要调整为
` - <%= config.subtitle %>`

但是要考虑到其他页面的标题应该是 页面标题+站点名称，还得改其他的地方

**Comment by adil-zhang** [comment]
```
<title>
    <%= page.title || config.title %>
    <% if (config.subtitle && is_home()){ %>
        - <%= config.subtitle %> 
    <% } else if (page.title && !is_home()){ %>
        | <%= config.title %>
    <% } %>
</title>
```
有其他更好的写法么

**Comment by rootlexme** [comment]
感谢您的反馈，已在dev分支修复
