### ISSUE TITLE
导航栏 menu 配置是英文时，间隙过宽

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#31]
如图所示
<img width="484" alt="image" src="https://user-images.githubusercontent.com/22308895/225644089-9b3423e7-35ee-4b21-8ad6-912c4d201a4b.png">

**Comment by adil-zhang** [comment]
导航栏最初的设计中确实未考虑到存在中英并存的情况，当您这边确实存在这个问题的话，可以自行引入CSS并添加以下内容：
`#menus > div > div:nth-child(1) > a > span {
  letter-spacing: 0rem;
}`
最后，考虑到当前开源优先级问题，可能在未来很久之后，我们会整体修复全站英文的情况。

**Comment by cunyu1943** [comment]
收到
