### ISSUE TITLE
首页顶部配置 banner 图标遮挡文字

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#32]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/22308895/225653335-3d25a482-7b8a-4c16-969a-0417a3bce45e.png">

另外，banner 是否可关闭？

这是设置为 false 后，显示一片空白

<img width="791" alt="image" src="https://user-images.githubusercontent.com/22308895/225654304-3972a35a-b9aa-4541-bc55-d9d54676dbb0.png">

**Comment by adil-zhang** [comment]
1.已在dev 分支实装banner开关并修复 
2.修复#34 中icon缺失导致的样式错乱问题
