### ISSUE TITLE
footer 右侧网易云和B站配置去不掉

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#33]
配置文件里边去掉了网易云和B站，但渲染结果还是有
<img width="942" alt="image" src="https://user-images.githubusercontent.com/22308895/225663124-d8c4e85c-9711-4887-9690-cf5e68e37475.png">

**Comment by rootlexme** [comment]
可能是主题的 `config.yml` 和您的 `_config.Acrylic.yml` 自动合并了

**Comment by cunyu1943** [comment]
这里优先级应该设置为 _config.Acrylic.yml 更高吧，而不是说合并？

**Comment by rootlexme** [comment]
`_config.Acrylic.yml` 如果不存在 `config.yml` 的参数便会自动合并，详情您可以查看一下 [Hexo](https://hexo.io/zh-cn/docs/configuration#%E4%BD%BF%E7%94%A8%E4%BB%A3%E6%9B%BF%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 的官方文档

**Comment by adil-zhang** [comment]
@rootlexblog 是不是主题配置文件这块默认注释掉吧，这个后面调整的人应该挺多的。

**Comment by rootlexme** [comment]
> @rootlexblog 是不是主题配置文件这块默认注释掉吧，这个后面调整的人应该挺多的。

确实

**Comment by cunyu1943** [comment]
又发现了些问题，如果把主题的默认配置（如 banner 的icon）注释掉了，编译之后打开就会样式乱了

**Comment by adil-zhang** [comment]
> 又发现了些问题，如果把主题的默认配置（如 banner 的icon）注释掉了，编译之后打开就会样式乱了

您上述提的问题已记录BUG并将会在稍晚点的版本修复，新问题请在新的issues下继续
