### ISSUE TITLE
footer 配置中的 group 样式

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#35]
配置较少时，能否优先居中，而不是优先左右分布
![](https://user-images.githubusercontent.com/22308895/225794915-9440e29f-5bb9-4d65-803f-8ffc31a44390.png)

![image](https://user-images.githubusercontent.com/22308895/225795492-2ae4c7ae-1728-45b5-af23-d1e10af844f0.png)

**Comment by rootlexme** [comment]
已在dev分支修复
