### ISSUE TITLE
文章默认封面

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#41]
默认封面是否能支持类似 butterfly 多个图片随机选择

**Comment by dc932dc** [comment]
- 文章随机封面且同一页面下不同图片的处理
- 配合图片api使用的参考例子 在文章头部cover属性配置
- 以 https://img.paulzzh.tech/touhou/random 为例
- 在末尾添加`?x`, 其中`x`是数字, 如: https://img.paulzzh.tech/touhou/random?233
- 此时这是两个完全不同的请求, 显示的图片即为不同的图片

@cunyu1943
