### ISSUE TITLE
footer 英文显示不完全

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#42]
如图，感觉中间的 Spring Boot 的 p 和 g 未显示完全，还是说字体就是这样的？
<img width="979" alt="image" src="https://user-images.githubusercontent.com/22308895/226084370-5951f476-f890-4e94-b1fb-ab399dd30f81.png">

**Comment by adil-zhang** [comment]
有线上地址可以看看吗

**Comment by cunyu1943** [comment]
> 有线上地址可以看看吗

https://cunyu1943.site/

**Comment by adil-zhang** [comment]
已在DEV中修复
