### ISSUE TITLE
文章页中文章目录无法跟随内容锚点高亮

### ISSUE THREAD

**Issue by adil-zhang** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#48]
<img width="309" alt="image" src="https://user-images.githubusercontent.com/55967755/226274587-0aa76e24-d980-4209-b621-f325c9b498e1.png">

**Comment by punglegod** [comment]
> <img alt="image" width="309" src="https://user-images.githubusercontent.com/55967755/226274587-0aa76e24-d980-4209-b621-f325c9b498e1.png">

你好，请问你使用主题时有报错吗。source文件现在下载不了，我这一直报错

**Comment by adil-zhang** [comment]
> <img alt="image" width="309" src="https://user-images.githubusercontent.com/55967755/226274587-0aa76e24-d980-4209-b621-f325c9b498e1.png">
> 你好，请问你使用主题时有报错吗。source文件现在下载不了，我这一直报错

请提供报错信息，建议您这边新建issues后提出您的问题并提供报错截图。
