### ISSUE TITLE
允许自定义主题色

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#56]
建议加入黑暗模式开关配置以及模式下颜色自定义（感觉黄色太亮了）

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/22308895/226955552-a34c937a-66e5-4856-b202-fef9bc409644.png">

**Comment by rootlexme** [comment]
其实您可以修改主题css中的 `var.css`

**Comment by cunyu1943** [comment]
> 

嗯嗯，这种的话我建议最好在文档里说下，可以在哪儿自定义 css，不然一般不会主动去看

**Comment by rootlexme** [comment]
好的，感谢您的反馈
