### ISSUE TITLE
个人的一些联系信息样式错误

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#61]
配置三个就会重叠
![image](https://user-images.githubusercontent.com/22308895/227437409-dd03ce86-d184-4aa3-9443-09f50c84c9c1.png)

**Comment by adil-zhang** [comment]
理解您想让用户使用中可以更快的找到您的相关联系方式，但是鉴于个人卡片的空间及视觉效果，建议您合理安排空间。
如：微信可以在下方flip中显示二维码更快找到您，个人主页中可以超链接至您的github主页等。
