### ISSUE TITLE
可以做一个安知鱼那样的相册功能吗？

### ISSUE THREAD

**Issue by xiangmingya** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#64]
![image](https://user-images.githubusercontent.com/70627786/227684473-3db737de-4b96-41e3-9393-14cb112f0a9c.png)

**Comment by xiangmingya** [comment]
O(∩_∩)O哈哈~。感谢！主要是想给猫猫做一个相册，自己搞不出来🤣感谢大佬认同！

**Comment by rootlexme** [comment]
不过个人觉得 https://blog.leonus.cn/photos/ 这种样式是否会更好

**Comment by xiangmingya** [comment]
嗯嗯嗯嗯，赞赞赞那
&nbsp;


冯湘铭呀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月25日(星期六) 下午3:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next] 可以做一个安知鱼那样的相册功能吗？ (Issue #64)





 
不过个人觉得 https://blog.leonus.cn/photos/ 这种样式是否会更好

**Comment by rootlexme** [comment]
好的，感谢您的建议
