### ISSUE TITLE
手机版页面头图自适应

### ISSUE THREAD

**Issue by xiangmingya** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#65]
![image](https://user-images.githubusercontent.com/70627786/227710025-9322c362-7fc6-46b5-87a0-9564e45ad02c.png)
![image](https://user-images.githubusercontent.com/70627786/227710059-2bba40bb-e274-4f3b-833a-9081b85b32b7.png)
感谢大佬们！

**Comment by adil-zhang** [comment]
感谢您的支持与建议，将在dev中优化
