### ISSUE TITLE
文章赞赏按钮中的赞赏者名单如何配置

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#70]
赞赏者名单如何配置？默认配置打开 404
![](https://user-images.githubusercontent.com/22308895/228466798-0d129350-04fb-4338-98a1-ea02288dd6fd.png)

**Comment by rootlexme** [comment]
![image](https://user-images.githubusercontent.com/59170489/228551404-6038aec8-b330-4f52-a941-815341d81695.png)

**Comment by adil-zhang** [comment]
@cunyu1943 目前赞赏者名单参考heo，在关于界面，添加相关配置项后可正常开启，详细阅读文档中关于界面配置项。
当然，如果您有更好的建议大家可以一起讨论。
