### ISSUE TITLE
能否增加一个洪哥那样的页脚底部呀？

### ISSUE THREAD

**Issue by tsiayigong** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#71]
![image](https://user-images.githubusercontent.com/63224494/228860514-3c664c24-4c90-455f-b746-535d8551224b.png)

**Comment by rootlexme** [comment]
![image](https://user-images.githubusercontent.com/59170489/228862306-c73f91e3-f0e0-4d93-b798-9023d5d00d48.png)
已经有了呀

**Comment by tsiayigong** [comment]
啊哈？为什么我滴没有捏，emmm，是我没有开哪个参数咩？
![image](https://user-images.githubusercontent.com/63224494/228865201-bcd1757b-b266-4645-932d-db2871a5a8ed.png)

**Comment by rootlexme** [comment]
是使用了adguard或者其他拦截器吗，如果有那就先关掉试试

**Comment by tsiayigong** [comment]
还真是诶，感谢大佬，我关掉Adblock就好了

**Comment by rootlexme** [comment]
嗯，不用谢
