### ISSUE TITLE
请问如何修改即刻短文的日期格式？

### ISSUE THREAD

**Issue by tsiayigong** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#72]
![image](https://user-images.githubusercontent.com/63224494/229054250-8fc259ad-3f7d-451e-99dd-375c64fbf41e.png)
我尝试过修改`<time class="datetime" datetime="<%= moment(item.date).format() %>"></time>`
为`<time class="datetime" datetime="<%= moment(item.date).format('YY-MM-DD') %>"></time>`，但是得到NaN，请问还需要改哪个地方么？
![image](https://user-images.githubusercontent.com/63224494/229054626-469ae9a7-8ac2-41fe-b66b-e74ad592b9ea.png)

**Comment by rootlexme** [comment]
![image](https://user-images.githubusercontent.com/59170489/229055926-d943d642-31dc-4c8d-968d-a26829858664.png)
需要修改`main.js`

**Comment by tsiayigong** [comment]
感谢大佬，搞定啦
