### ISSUE TITLE
sitename 样式问题

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#74]
<img width="182" alt="image" src="https://user-images.githubusercontent.com/22308895/229262062-f80a551d-fa37-44fc-952a-2ce0e0c5b1b0.png">

**Comment by rootlexme** [comment]
@adil-zhang

**Comment by adil-zhang** [comment]
已在最新版DEV中修复
