### ISSUE TITLE
about 页评论关不掉

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#76]
- 配置
<img width="545" alt="image" src="https://user-images.githubusercontent.com/22308895/229262913-5ba6d0b8-3803-41f9-8277-1580d4c655cb.png">
- 效果

<img width="1619" alt="image" src="https://user-images.githubusercontent.com/22308895/229262939-99241b5b-2928-4d09-9d50-a93677491d1a.png">

**Comment by rootlexme** [comment]
comment: false
