### ISSUE TITLE
about页面缺少内容

### ISSUE THREAD

**Issue by pzjawa** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#77]
狼人杀缺少icon内容，导致about.yml的game2的icon配置项不生效
![Snipaste_2023-04-01_11-13-20](https://user-images.githubusercontent.com/113767212/229263071-86b79b9b-7e90-4b9c-9571-a0094863fae5.png)

**Comment by adil-zhang** [comment]
已在deV中修复，感谢您的反馈
