### ISSUE TITLE
文章cover取色如何保持个人卡片颜色不变

### ISSUE THREAD

**Issue by Aaron-zsy** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#78]
文章cover取色如何保持个人卡片颜色不变

**Comment by adil-zhang** [comment]
在[卡人卡片颜色](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/blob/main/source/css/main.css#L9179)这里您会看到个人卡片由多种颜色生成线性渐变，而[cover取色](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/blob/dev/source/js/extend/covercolor/web.js#L17)您会看到卡片所需要的相关颜色都根据文章主色做了调整。
为保证移植的完整性，我们暂时不考虑调整这块内容。

综上，您如果想要保证个人卡片颜色不变，您可能需要调整相关样式，您引入新的CSS并对以下内容进行调整：
`#aside-content>.card-widget.card-info::before {
  background: 调整为您想需要的颜色
}`
