### ISSUE TITLE
about 页生涯图片

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#80]
图片应该是限定在一定位置，而不是图片多大显示多大吧
<img width="721" alt="image" src="https://user-images.githubusercontent.com/22308895/229275060-770d3e0f-dd5d-4789-8586-63a4680d798a.png">
<img width="771" alt="image" src="https://user-images.githubusercontent.com/22308895/229275138-bc3cc13b-9477-4873-abfc-d9e2fda56923.png">

**Comment by cunyu1943** [comment]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/22308895/229275316-e6c4421e-2200-4734-8c98-57e6f364a64f.png">

**Comment by adil-zhang** [comment]
这个问题的原因是CSS规则与内联样式之间存在优先级的冲突。
about页面最晚将会在下周三进行重构完毕，给您带来的困扰非常抱歉。
