### ISSUE TITLE
Limitation on the number of sticky articles causes coverage

### ISSUE THREAD

**Issue by dc932dc** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#81]
当置顶文章`recommend: true`的文章数量超过6篇时 出现此现象
![图片](https://user-images.githubusercontent.com/46415893/229275628-7eef7603-5b2b-4152-a176-ca8f3a49fe61.png)

**Comment by rootlexme** [comment]
感谢您的反馈，后续会限制最大文章数量

**Comment by adil-zhang** [comment]
已在dev中修复，感谢您的反馈
