### ISSUE TITLE
关于页头像设置不生效

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#82]
- 配置及效果
authorinfo:
  image: /img/logo.svg

<img width="709" alt="image" src="https://user-images.githubusercontent.com/22308895/229275680-df062344-0b87-4452-b1df-50d282c18c5b.png">

- logo.svg 原图
<img width="657" alt="image" src="https://user-images.githubusercontent.com/22308895/229275769-dec41fdf-3c40-4822-b20d-d0e93cc21eed.png">

**Comment by adil-zhang** [comment]
已在DEV中修复
