### ISSUE TITLE
footer 订阅设置缺失

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#87]
生成 rss 的配置 & 插件是不是还没
<img width="303" alt="image" src="https://user-images.githubusercontent.com/22308895/229335593-b2bf3f65-a1d5-4d8b-a849-f92443b21f91.png">

**Comment by rootlexme** [comment]
需要安装插件 `npm install hexo-generator-feed --save`

**Comment by dc932dc** [comment]
dev分支下主题配置无rss配置
doc文档无rss教程内容
待补充
