### ISSUE TITLE
音乐胶囊样式问题

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#88]
=.=
<img width="618" alt="image" src="https://user-images.githubusercontent.com/22308895/229336740-b9ad98c9-d8c7-48ab-88e0-8d68514597d0.png">

**Comment by adil-zhang** [comment]
请详细描述您的相关问题

**Comment by adil-zhang** [comment]
查看了您的相关内容，发现您是在引入第三方插件时，样式表中#readmore-wrapper中的z-index过大，导致音乐胶囊被遮挡，请调整相关样式。

**Comment by cunyu1943** [comment]
🆗
