### ISSUE TITLE
友链页按钮功能无效

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#89]
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/22308895/229336824-7bc41de2-0fa4-43de-b3fc-c6683b6b650d.png">

**Comment by adil-zhang** [comment]
@rootlexblog 
这得新增两函数

**Comment by cyolc932** [comment]
随机访问可用
添加友链无内容跳转

**Comment by adil-zhang** [comment]
已在https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/commit/905040acc59f732d9d2c595a7ccbc7bcc562c287修复
