### ISSUE TITLE
文章版权建议

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#95]
能否设置为左边/右边可以设置二维码的形式，如下
![image](https://user-images.githubusercontent.com/22308895/229489568-729e75be-a8bd-4bb2-a0de-bb615bfbf4d8.png)

**Comment by adil-zhang** [comment]
二维码展示内容？具体需求是什么。

**Comment by cunyu1943** [comment]
<img width="988" alt="image" src="https://user-images.githubusercontent.com/22308895/229513395-c3f2541c-7b89-4b8c-87b5-1353d2f92325.png">

**Comment by adil-zhang** [comment]
二维码具体是什么内容？如果是本文链接的话，文章结尾有相关的内容。

**Comment by cunyu1943** [comment]
微信/公众号/群之类的

**Comment by adil-zhang** [comment]
> 微信/公众号/群之类的

这个需求似乎有些个性化，您可以自行将您需要的内容放在上面。
