### ISSUE TITLE
The problem of dislocation of styles on the mobile terminal

### ISSUE THREAD

**Issue by dc932dc** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#97]
多浏览器测试均复现样式错位
Firefox/Chrome/qq浏览器
|![图片](https://user-images.githubusercontent.com/46415893/229534148-b24d7933-71fd-42ba-8800-2feeaf69b36b.png)|![图片](https://user-images.githubusercontent.com/46415893/229534277-a142771a-f0af-4a2b-adf7-084685da6b9a.png)|
|-|-|

**Comment by adil-zhang** [comment]
已在DEV修复
