### ISSUE TITLE
文章没有标题时，文章目录不会隐藏

### ISSUE THREAD

**Issue by Cystee** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#99]
https://mirror.casecori.top/%E5%85%B3%E4%BA%8E%E6%89%93%E8%B5%8F%E5%8A%9F%E8%83%BD%E7%9A%84%E6%80%9D%E8%80%83.html

![image](https://user-images.githubusercontent.com/61391190/229749601-893e1a5c-1849-42c6-8e17-018f815ebf70.png)

**Comment by adil-zhang** [comment]
已在DEV中修复
